# Generated by Django 4.1.6 on 2023-02-06 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameAllergy', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='date of birth')),
                ('sex', models.CharField(max_length=1)),
                ('address', models.CharField(max_length=200)),
                ('allergy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allergy.allergy')),
            ],
        ),
    ]
